name: SimpleCommands
version: 1.0-SNAPSHOT
main: com.wsdev.simpleCommands.SimpleCommands
api-version: 1.21

Site:
  Exigir-Permissao: false
  Mensagem: "&aSite do nosso servidor: &ewww.brunnofdc.dev.br"
