name: SimpleCommands
version: '1.0-SNAPSHOT'
main: com.wsdev.simpleCommands.SimpleCommands
api-version: '1.21'

commands:
  site:
    description: "Envia o site do servidor no chat."
  fly:
    description: "Permite ativar o fly."
    usage: /fly
  gm:
    description: "Altere o moto de jogo para survival ou criativo."
    usage: /gm ( 0 - 1 )
